### ISSUE TITLE
Slow corpus reading

### ISSUE THREAD

**Issue by slavaGanzin** [anyks/asc#6]
Hello

Best LM ever. Feel very lucky that I decide to search for something other than KenLM/SRILM. 
Thanks for your work!

So, I have 10Gb of corpuses. But when I tried to load just 58Mb one (1262705 one liners) I get 30 minutes estimate on loading text corpus. Why so? 

And how could I crunch my 10GB?

Here is a command:
```
asc -alphabet "abcdefghijklmnopqrstuvwxyzабвгдеёжзийклмнопрстуфхцчшщъыьэюя" -size 3 -smoothing wittenbell -method train -debug 1 -w-arpa ./lm.arpa -w-map ./lm.map -w-vocab ./lm.vocab -w-ngram ./lm.ngrams -allow-unk -interpolate -corpus ./corpus.txt
```

p.s. Literally, don't get why you have so little stars on GitHub and zero exposure.

**Comment by anyks** [comment]
Hello! The running time is estimated approximately, the fact is that it is impossible to load from a file line by line in multithreaded mode. After the strings are loaded into memory, the generation of the language model is already done in multithreaded mode.

**Comment by slavaGanzin** [comment]
Just tested KenLM. It processed the same file in 6 seconds.

I know that asc has all this additional tokens as <punkt>, but difference in speed is dramatic.

Besides, can I use arpa model to generate .asc file? If I have only probabilities of coocurance of n-grams and not corpus. Can I emulate arpa file and create spelling correction model? Or can I just load .arpa into asc?

**Comment by anyks** [comment]
There is no tokenization in kenlm, it is tokenization that eats up 90% of the processing time, moreover, in kenlm you need to perform n-grams alignment. Yes, you can use a ready-made arpa file. There are examples on github.

It takes a long time only to train the model; in the future, work with models is faster than in other language models.

**Comment by slavaGanzin** [comment]
So can I disable tokenization? And what would I loose from that?

And another question: if I want emulate skip-gram would it be enough to do
`
asc.spell(“the world is <unk> enough”)
`

**Comment by anyks** [comment]
Yes! You can disable the tokenizer, it is necessary for processing complex and dirty texts that contain errors and many characters that are not related to n-grams.
<unk> - Means that the word is not in the dictionary, i.e. it is unknown. If you need to skip some words, you can use the black and white list of words, for example: "addBadword(...)".

**Comment by slavaGanzin** [comment]
Thanks for your help!
